version: '3'

services:
  app:
    image: kerry91/nodeblogapp:1.0
    ports:
      - "3000:3000"
    restart: always
    links:
      - mongo
    volumes:  
      - myremotevolume:/user/src/app
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"

volumes:   
  myremotevolume: